version: "2"
services:
  db:
    image: postgres:10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: some-user
      POSTGRES_PASSWORD: some-password
      POSTGRES_DB: some-db
      PGDATA : /var/lib/postgresql/data
    volumes:
    - ./data:/var/lib/postgresql/data
    logging:
      options:
        max-size: "12m"
        max-file: "5"
      driver: json-file

